# Generated by Django 4.2.11 on 2024-05-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=123, upload_to='project_images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
